using System.Collections.Generic;
using Xunit;

namespace Problems.Tests
{
    /*
    Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.

    */

    public class Problem2Tests
    {
        [Fact]
        public void ReturnsCorrectEvenNumberFibonacci_WhenTopNumberIs89()
        {
            var classUnderTest = new Problem2();
            var expected = new List<int> {2, 8, 34};

            var actual = classUnderTest.GetFibonacciSequence(89);

            Assert.Equal(expected,actual);
        }
    }
}