using System.Collections.Generic;
using Xunit;

namespace Problems.Tests
{
    /*
    Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.

    */

    public class Problem2Tests
    {
        [Theory]
        [InlineData(2, 2)]
        [InlineData(10, 10)]
        [InlineData(89, 44)]
        [InlineData(4000000, 4613732)]
        public void ReturnsCorrectEvenNumberFibonacciSum(int topNumber, int expected)
        {
            var classUnderTest = new Problem2();

            var actual = classUnderTest.GetFibonacciSequence(topNumber);

            Assert.Equal(expected,actual);
        }
    }
}